export const documentacion = {
    konfio: {
        pm: {
            creditoS: [
                'IDENTIFICACIÓN DE UN ACCIONISTA CON UN MÍNIMO DE 25% DE ACCIONES',
                'RFC CON EL QUE FACTURAS Y CONTRASEÑA DEL SAT',
                'ACTA CONSTITUTIVA CON FOLIO DEL RPP',
                'ASAMBLEAS CON FOLIO DEL RPP  (EN CASO DE APLICAR)',
                'COMPROBANTE DE DOMICILIO DEL NEGOCIO',
                'CONSTANCIA DE SITUACIÓN FISCAL DE LA EMPRESA',
                'REP LEGAL INE, PASAPORTE O RESIDENCIA PERMANENTE EN CASO DE EXTRAJERO (VIGENTES Y ESCANEADOS EN PDF)',
                'REP LEGAL COMPROBANTE DE DOMICILIO',
                'OBL SOL INE, PASAPORTE O RESIDENCIA PERMANENTE EN CASO DE EXTRAJERO (VIGENTES Y ESCANEADOS EN PDF)',
                'OBL SOL COMPROBANTE DE DOMICILIO',
            ],
            tdcEmpresario: [
                'IDENTIFICACIÓN DE UN ACCIONISTA CON UN MÍNIMO DE 25% DE ACCIONES',
                'RFC CON EL QUE FACTURAS Y CONTRASEÑA DEL SAT',
                'ACTA CONSTITUTIVA CON FOLIO DEL RPP',
                'ASAMBLEAS CON FOLIO DEL RPP  (EN CASO DE APLICAR)',
                'COMPROBANTE DE DOMICILIO DEL NEGOCIO',
                'CONSTANCIA DE SITUACIÓN FISCAL DE LA EMPRESA',
                'REP LEGAL INE, PASAPORTE O RESIDENCIA PERMANENTE EN CASO DE EXTRAJERO (VIGENTES Y ESCANEADOS EN PDF)',
                'REP LEGAL COMPROBANTE DE DOMICILIO',
                'OBL SOL INE, PASAPORTE O RESIDENCIA PERMANENTE EN CASO DE EXTRAJERO (VIGENTES Y ESCANEADOS EN PDF)',
                'OBL SOL COMPROBANTE DE DOMICILIO',
            ],
            },
        pfae: {
            creditoS: [
                'INE, PASAPORTE O RESIDENCIA PERMANENTE EN CASO DE EXTRAJERO (VIGENTES Y ESCANEADOS EN PDF)',
                'RFC CON EL QUE FACTURAS Y CONTRASEÑA DEL SAT',
                'COMPROBANTE DE DOMICILIO DEL NEGOCIO O CONSTACIA DE SITUACIÓN FISCAL'
            ],
            tdcEmpresario: [
                'INE, PASAPORTE O RESIDENCIA PERMANENTE EN CASO DE EXTRAJERO (VIGENTES Y ESCANEADOS EN PDF)',
                'RFC CON EL QUE FACTURAS Y CONTRASEÑA DEL SAT',
                'COMPROBANTE DE DOMICILIO DEL NEGOCIO O CONSTACIA DE SITUACIÓN FISCAL'
            ],
        }
    },
    covalto: {
        viabilidad: [
            'BURÓ DE CRÉDITO TANTO DEL ACREDITADO COMO DEL AVAL',
            'ESTADOS FINANCIEROS DE LOS ÚLTIMOS DOS CIERRES DE AÑOS Y PARCIALES',
            'CUADRO DE PASIVOS ACTUALIZADO',
            'CURRICULUM VITAE (CV)'
        ],
        pm: {
            CreditoSimpleRevolventeConGarantia: [
                'SOLICITUD DE CRÉDITO COMPLETA Y FIRMADA',
                'ACTA CONSTITUTIVA CON RPP',
                'ASAMBLEAS Y/O PODERES COMPLETAS',
                'AUTORIZACIÓN DE CONSULTA DE BURÓ (ACREDITADO, PF, PM, RL, OS, ACCIONISTAS, GARANTES)',
                'BURÓ FIRA (EN CASO DE QUE APLIQUE)',
                'KYC (ACREDITADO, PF, PM, RL, OS, ACCIONISTAS, GARANTES)',
                'KYC AMPLIADO (EN CASO DE SER UN CLIENTE QUE REPRESENTE ALGÚN RIESGO)',
                'CONSTANCIA DE SITUACIÓN FISCAL (NO MAYOR A 3 MESES) (ACREDITADO, ACCIONISTA, REP LEGAL O GARANTE)',
                'INE / PASAPORTE / EXTRANJERO FM2 (ACREDITADO, ACCIONISTA, REP LEGAL O GARANTE)',
                'ACTA DE MATRIMONIO (CUANDO APLIQUE)',
                'IDENTIFICACIÓN DEL CÓNYUGE (CUANDO APLIQUE)',
                'CURP (ACCIONISTA, REP LEGAL O GARANTE)',
                'COMPROBANTE DE DOMICILIO (NO MAYOR A 3 MESES) (DEBE DE COINCIDIR CONTRA SOLICITUD Y KYC)',
                'ÚLTIMOS 3 ESTADOS DE CUENTA (EN CASO DE SER CLIENTES SE PODRÁN UTILIZAR HASTA ANTERIORES 2 AÑOS)',
                'ESTADO FINANCIERO COMPLETO DE LOS ÚLTIMOS DOS AÑOS Y PARCIAL DEL AÑO EN CURSO, FIRMADOS POR RL CON ANALÍTICAS (ACREDITADO Y COACREDITADO SI APLICA) (REVISAR TABLA DE PERIODOS EXIGIBLES)',
                'VALIDACIÓN SAT https://clientes.credijusto.com/',
                'AVISO DE PRIVACIDAD FIRMADO (ACREDITADO, PF, PM, RL, OS, ACCIONISTAS, GARANTES)',
                'ESCRITURA O TÍTULO DE PROPIEDAD (PRIMER TESTIMONIO CON RPP Y DATOS DE SUPERFICIE, MEDIDAS Y COLINDANCIAS)',
                'CERTIFICACIONES Y CERTIFICADOS LIBRES DE GRAVAMEN',
                'SOLICITUD DE AVALÚO',
                'BACKLOG (CUANDO EL ACREDITADO TIENE FUNCIONES A TRAVÉS DE CONTRATOS)',
                'PROPUESTA INDICATIVA',
                'BOLETA DE AGUA (CON SELLO DE PAGADO O CONSTANCIA DE NO ADEUDO)',
                'BOLETA DE PREDIAL',
                'REPORTE DE VISITA OCULAR',
                'FORMATO DE COTEJO DE DOCUMENTOS',
                'CARTA SALDO DE LOS PASIVOS (SI TIENE AUTORIZADO PAGO DE PASIVOS)',
                'APERTURA DE CUENTA COVALTO',
                'PLAN DE NEGOCIOS',
            ],
        },
        pfae: {}
    }
}